### ISSUE TITLE
Link help articles together

### ISSUE THREAD

**Issue by JorgenEvens** [ambassify/help#48]
We currently have tons of broken links for articles that have been written in the last sprint.

**Comment by Sitebase** [comment]
@JorgenEvens it's probably a good idea to add some sort of test that checks the status of all links to make sure we don't end up with a bunch of dead links in our documentation.

**Comment by JorgenEvens** [comment]
Agreed, do you know of any such tools that can do this "offline"?

**Comment by Sitebase** [comment]
Nope, don't know about offline. But we should also check external links to blog posts and such.
For this we can probably use `wget`.

**Comment by Gertt** [comment]
`curl` ftw!

**Comment by JorgenEvens** [comment]
Was thinking about something like that as well in combination with `python -mjson.tool`

**Comment by Sitebase** [comment]
@Gertt you can let `wget` spider your website which is easier.
